name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deployment:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Copy files to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }} //secrets är adressen till aws  först lägga till i secrets i github. Ska ha namnet HOST (NEW REPOSITORY SECRET)
          username: ${{ secrets.USER }}
